# Generated by Django 5.2.9 on 2026-01-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.CharField(default='Low', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('WASTE', 'Waste Accumulation'), ('TRAFFIC', 'Traffic Bottleneck'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cityzone')),
            ],
        ),
        migrations.CreateModel(
            name='AgriSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50)),
                ('quantity_kg', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('farmer_name', models.CharField(max_length=100)),
                ('spoilage_risk_score', models.FloatField(default=0.0)),
                ('origin_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cityzone')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_beds_icu', models.IntegerField(default=20)),
                ('occupied_beds_icu', models.IntegerField(default=0)),
                ('total_beds_general', models.IntegerField(default=100)),
                ('occupied_beds_general', models.IntegerField(default=0)),
                ('oxygen_supply_level', models.IntegerField(default=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cityzone')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('congestion_level', models.FloatField(default=0.0)),
                ('is_road_closed', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cityzone')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.FloatField()),
                ('precipitation_mm', models.FloatField()),
                ('wind_speed_kmh', models.FloatField()),
                ('visibility_km', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='core.cityzone')),
            ],
        ),
    ]
