# Generated by Django 5.2.9 on 2026-01-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospital_is_live_data_weatherlog_co_weatherlog_no2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherlog',
            name='co',
        ),
        migrations.RemoveField(
            model_name='weatherlog',
            name='no2',
        ),
        migrations.RemoveField(
            model_name='weatherlog',
            name='ozone',
        ),
        migrations.RemoveField(
            model_name='weatherlog',
            name='pm10',
        ),
        migrations.RemoveField(
            model_name='weatherlog',
            name='pm25',
        ),
        migrations.RemoveField(
            model_name='weatherlog',
            name='so2',
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='pollutant_details',
            field=models.TextField(default='{}'),
        ),
    ]
