# Generated by Django 6.0.1 on 2026-01-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_weatherlog_co_remove_weatherlog_no2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_speed', models.IntegerField()),
                ('free_flow_speed', models.IntegerField()),
                ('current_travel_time', models.IntegerField()),
                ('free_flow_travel_time', models.IntegerField()),
                ('congestion_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('road_class', models.CharField(max_length=20)),
                ('road_closure', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_traffic', to='core.cityzone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
