# Generated by Django 6.0.1 on 2026-01-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_realtimetraffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenreport',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='latitude',
            field=models.FloatField(default=28.6139),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='longitude',
            field=models.FloatField(default=77.209),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
