# Generated by Django 5.2.9 on 2026-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cityzone_average_income_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityzone',
            name='area_type',
            field=models.CharField(default='Mixed', max_length=50),
        ),
    ]
