# Generated by Django 5.2.9 on 2026-01-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cityzone_area_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_live_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='co',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='no2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='ozone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='so2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
