# Generated by Django 5.2.9 on 2026-01-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_aadhar_number_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenreport',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='latitude',
            field=models.FloatField(default=28.6139),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='longitude',
            field=models.FloatField(default=77.209),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
