# Generated by Django 6.0.1 on 2026-01-17 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('farmer_name', models.CharField(max_length=100)),
                ('crop_name', models.CharField(max_length=50)),
                ('quantity_kg', models.FloatField()),
                ('quality_scan', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('transit_hours', models.FloatField(default=0.0)),
                ('current_temp_exposure', models.FloatField(default=24.0)),
                ('spoilage_risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('VERIFIED', 'Verified')], default='IN_TRANSIT', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
